---
- name: Create Google Cloud Instance 
  hosts: localhost 
  become: yes 
  vars: 
    machine_name: master1
    google_project_id: trusty-vim-463004-j2
    # location where you put the service account.json file 
    service_account_path: /home/sivthingthing.com/.ssh/devops/devops_gen09_weekend/ansible-related/iaC/service_account.json
    ssh_public_key_path: /home/sivthingthing.com/.ssh/id_rsa.pub
    
  tasks:
    - name: create first gcp instance 
      import_tasks: tasks/create-gcp-task.yaml
# ansible-playbook playbooks/create-gcp-instance.yaml