- name: Install Python packages in a virtual environment
  hosts: localhost
  become: true
  tasks:
    - name: Ensure python3-venv is installed
      apt:
        name: python3-venv
        state: present

    - name: Create virtual environment
      command: python3 -m venv /opt/myenv
      args:
        creates: /opt/myenv

    - name: Install packages in virtualenv
      pip:
        name:
          - requests
          - google-auth
        virtualenv: /opt/myenv
